### ISSUE TITLE
upgrade styled-jsx dependency to v1.

### ISSUE THREAD

**Issue by Tomekmularczyk** [giuseppeg/styled-jsx-postcss#19]
Is there any chance this package will get updated with new version of styled-jsx?

**Comment by iamdevonbutler** [comment]
+1

**Comment by klaygomes** [comment]
This will help to fix this issue too: [TypeError: after.after is not a function](https://github.com/postcss/postcss-nested/issues/54)

**Comment by giuseppeg** [comment]
I don't have time to do this unfortunately, PR are welcome!
